export enum NomenclatureTypeEnum {
  wheelRimTyreCategories = 'wheelRimTyreCategories',
  motorcycleCategories = 'motorcycleCategories',
  accessoryCategories = 'accessoryCategories',
  introductionDates = 'introductionDates',
  enginePowerTypes = 'enginePowerTypes',
  transactionTypes = 'transactionTypes',
  annonceFormats = 'annonceFormats',
  vanCategories = 'vanCategories',
  chassisTypes = 'chassisTypes',
  accountTypes = 'accountTypes',
  currencies = 'currencies',
  languages = 'languages',
  itemTypes = 'itemTypes',
  gearboxes = 'gearboxes',
  countries = 'countries',
  tireTypes = 'tireTypes',
  rimTypes = 'rimTypes',
  months = 'months',
  fuels = 'fuels',
}
